// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yprsxpiqzdelmxslpgyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwcnN4cGlxemRlbG14c2xwZ3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjc5MzAsImV4cCI6MjA3Nzc0MzkzMH0.DtifFYNLHcu8Ps2UY-OuArY9ioLPPtDn1uDfUz_xW4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});